export const USER_REPO = 'USER_REPO';
export const USER_PROFILE_REPO = 'USER_PROFILE_REPO';
export const USER_GROUP_REPO = 'USER_GROUP_REPO';
export const SESSION_REPO = 'SESSION_REPO';
export const TOKEN_SERVICE = 'TOKEN_SERVICE';
export const PASSWORD_HASHER = 'PASSWORD_HASHER';

export const ZONE_REPO = 'ZONE_REPO';
export const BRANCH_REPO = 'BRANCH_REPO';
export const WAREHOUSE_REPO = 'WAREHOUSE_REPO';
export const COMPANY_REPO = 'COMPANY_REPO';
export const VISIBILITY_SERVICE = 'VISIBILITY_SERVICE';

export const COUNTRY_REPO = 'COUNTRY_REPO';
export const CURRENCY_REPO = 'CURRENCY_REPO';
export const EXCHANGE_RATE_REPO = 'EXCHANGE_RATE_REPO';
export const DEPARTMENT_REPO = 'DEPARTMENT_REPO';
export const JOB_TITLE_REPO = 'JOB_TITLE_REPO';
